name: Test OCI Connection
on: [push]

jobs:
  oci-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup OCI CLI
        uses: oracle-actions/setup-oci-cli@v1.3.2
        with:
          user: ${{ secrets.OCI_USER_OCID }}
          tenancy: ${{ secrets.OCI_TENANCY_OCID }}
          fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          region: ${{ secrets.OCI_REGION }}
          api_key: ${{ secrets.MY_PRIVATE_KEY }}

      - name: Verify Connection
        run: oci iam region list --output table
